# Generated by Django 5.0.7 on 2024-07-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.AddField(
            model_name='contract',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.userprofile'),
            preserve_default=False,
        ),
    ]
