# Generated by Django 5.0.7 on 2024-07-16 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_contract_user_contract_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
